### ISSUE TITLE
Default to player 2

### ISSUE THREAD

**Issue by zach-morris** [kodi-game/game.libretro.beetle-bsnes#3]
The controller buttonmap appears correct with build 2016-01-09, however I attempted to play Mario Kart today and couldn't start a one player game for some reason.  I could start a two player game, and finally saw that my controller was mapped as the second player.  This was without any configuration for two player, and I only have one controller plugged into my machine.  Same was true for SNES9x and 9x-next.  I wasn't able to start Mario Kart with Mercury (hangs at a black screen), so was unable to test.

**Comment by garbear** [comment]
Can this be closed?

**Comment by zach-morris** [comment]
Yep
